spring.application.name=Bambinou
# DB Configuration :
spring.datasource.url=jdbc:mysql://localhost:3306/Bambino?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
debug=true

# Web Server (Tomcat) configuration :
server.address=0.0.0.0

server.port=8089

logging.level.org.springframework.security=DEBUG


# 1h in millisecond
security.jwt.expiration-time=3600000



# Configuration de l'email (par exemple, avec Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=selim03gaaloul@gmail.com
spring.mail.password=rzbb fmbe bzvm tsth

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

#config de thymeleaf pour les templates html dans les emails
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false  
#D�sactiver le cache pendant le d�veloppement


#config pour connextion avec google




#config recaptcha

#cote spring : 6LehzhMrAAAAACdubeyPbA2xpqQXuVGmzbBPzJ6d
#cote client : 6LehzhMrAAAAADxRyVo1MeCuU-V90P5TYYV2VDxj